repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: Python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: v3.8.1
    hooks:
    - id: flake8
